### ISSUE TITLE
Packaging this with a Laravel App

### ISSUE THREAD

**Issue by leothelocust** [vcarreira/docker-laravel#2]
First off, thanks for this very well designed group of docker images/containers.

I do have a question tho.  How would a person go about packaging this up into a Laravel Project so other devs could quickly `docker-compose up -d` after a simple `git clone`of the Laravel project.

It seems docker is meant for such a task, but this particular example seems to aim towards keeping the docker-compose.yml file out of the Laravel repo.

Thoughts?

**Comment by vcarreira** [comment]
Hi, I understand your issue and I'm working on a Yo generator to simplify the process of "dockerizing" a full stack Laravel app. Something as simple as: yo docker-laravel from your laravel folder.

I'm planning on releasing it next week.

**Comment by vcarreira** [comment]
You can checkout my new yeoman generator that simplifies the process of dockerizing a Laravel App [/vcarreira/generator-docker-laravel](https://github.com/vcarreira/generator-docker-laravel)
